---
baseUrl:                "http://cinematt.dev"
languageCode:           "en-ie"
title:                  "[DEV] Cinematt"
disableLiveReload:      true
watch:                  true
preservetaxonomynames:  true

params:
  description:          "Photography website"
  author:               "Matt Finucane"
  cl_media_base:        "https://res.cloudinary.com/matt-finucane-portfolio/"
  noindex:              true
...

